### ISSUE TITLE
遇到一些小问题~

### ISSUE THREAD

**Issue by Mikry-afk** [API-Security/APISandbox#2]
1. API1: BrokenObjectLevelAuthorization
需要登录用户身份会话进行遍历ID。无登陆菜单。使用 /v2/login 一直未成功。
2.get访问/v2/login提示404
![image](https://user-images.githubusercontent.com/56582129/147456270-8493a1b7-26b6-4db2-8180-f2bfd8505593.png)

**Comment by Anthem-whisper** [comment]
请使用POST方法访问`/v2/login `
