### ISSUE TITLE
Infosystem中数据库连接出现问题？

### ISSUE THREAD

**Issue by CMredkulaa** [API-Security/APISandbox#3]
无法访问wsdl
![7c71c0dfcef7fc3e453be1a0998174e](https://user-images.githubusercontent.com/58243601/148896232-0d0053ff-471e-4271-940e-78ace4d5a291.png)
![434a60ed9ecc1d68fe664fa00e2cad4](https://user-images.githubusercontent.com/58243601/148896263-164e2075-c575-441c-b0bb-f9d25ba3acac.png)

**Comment by F4ded** [comment]
> 无法访问wsdl ![7c71c0dfcef7fc3e453be1a0998174e](https://user-images.githubusercontent.com/58243601/148896232-0d0053ff-471e-4271-940e-78ace4d5a291.png) ![434a60ed9ecc1d68fe664fa00e2cad4](https://user-images.githubusercontent.com/58243601/148896263-164e2075-c575-441c-b0bb-f9d25ba3acac.png)

我本地测试没有出现该问题，请检查是否是部署出现了问题？
![image](https://user-images.githubusercontent.com/66620626/149470504-6db8b226-38c5-4ab3-88e2-7d9ba8114f6b.png)
